version: '3.8'

services:
  kafka-exporter:
    image: danielqsj/kafka-exporter:latest
    container_name: kafka-exporter
    ports:
      - "9308:9308"
    environment:
      - KAFKA_SERVER=kafka1:19091,kafka2:19091,kafka3:19091
    command:
      - '--kafka.server=kafka1:19091'
      - '--kafka.server=kafka2:19091'
      - '--kafka.server=kafka3:19091'
    networks:
      - kafka_network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - kafka_network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - kafka_network

networks:
  kafka_network:
    external: true
